name: Security Pipeline

on:
  push:
    branches:
      - main
      - D3
  pull_request:
    branches:
      - main
      - D3
jobs:
  security-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Python Set Up 
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: |
          pytest tests/ --import-mode=importlib
        env:
          PYTHONPATH: ${{ github.workspace }}

      # bandit analysis of static code
      - name: Static Code Analysis with Bandit
        run: | 
          pip install bandit && bandit -r .

      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install pip-audit
        run: pip install pip-audit
      - name: Run pip-audit
        run: pip-audit

      - name: Secrets Scanning with Gitleaks
        uses: zricethezav/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Install Snyk
        run: npm install -g snyk

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --file=requirements.txt --policy-path=.snyk
